<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <!-- Avalonia stuff -->
    <PropertyGroup>
        <!-- enable private APIs -->
        <AvaloniaAccessUnstablePrivateApis>true</AvaloniaAccessUnstablePrivateApis>
        <Avalonia_I_Want_To_Use_Private_Apis_In_Nuget_Package_And_Promise_To_Pin_The_Exact_Avalonia_Version_In_Package_Dependency>true</Avalonia_I_Want_To_Use_Private_Apis_In_Nuget_Package_And_Promise_To_Pin_The_Exact_Avalonia_Version_In_Package_Dependency>
    </PropertyGroup>
    <ItemGroup>
      <ProjectReference Include="..\..\..\src\Avalonia.Base\Avalonia.Base.csproj" />
      <ProjectReference Include="..\..\..\src\Avalonia.Controls\Avalonia.Controls.csproj" />
    </ItemGroup>

</Project>
